global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#igor_buldashov'
