# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata: # Блок метаданных деплоя
#   name: ui
#   labels:
#     app: reddit
#     component: ui
# spec: # Блок спецификации деплоя
#   replicas: 3
#   selector:
#     matchLabels:
#       app: reddit
#       component: ui
#   template: # Блок описания POD-ов
#     metadata:
#       name: ui-pod
#       labels:
#         app: reddit
#         component: ui
#     spec:
#       containers:
#       - image: ge2rg312qe/ui # Не забудьте подставить свой образ
#         name: ui
#         env:
#         - name: ENV
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.namespace
# Page-17
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: reddit
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui
      labels:
        app: reddit
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: ge2rg312qe/ui # Не забудьте подставить свой образ
        name: ui
        ports:
        - containerPort: 9292
          name: ui
          protocol: TCP
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
