# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata: # Блок метаданных деплоя
#   name: ui
#   labels:
#     app: reddit
#     component: ui
# spec: # Блок спецификации деплоя
#   replicas: 3
#   selector:
#     matchLabels:
#       app: reddit
#       component: ui
#   template: # Блок описания POD-ов
#     metadata:
#       name: ui-pod
#       labels:
#         app: reddit
#         component: ui
#     spec:
#       containers:
#       - image: ge2rg312qe/ui # Не забудьте подставить свой образ
#         name: ui
#         env:
#         - name: ENV
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.namespace
# Page-17
---
#apiVersion: apps/v1
##apiVersion: networking.k8s.io/v1
#kind: Deployment
#metadata: # Блок метаданных деплоя
#  name: {{ .Release.Name }}-{{ .Chart.Name }}
#  labels:
#    app: reddit
#    component: ui
#    release: {{ .Release.Name }}
#spec: # Блок спецификации деплоя
#  replicas: 3
#  strategy:
#    type: Recreate
#  selector:
#    matchLabels:
#      app: reddit
#      component: ui
#      release: {{ .Release.Name }}
#  template: # Блок описания POD-ов
#    metadata:
#      name: ui
#      labels:
#        app: reddit
#        component: ui
#        release: {{ .Release.Name }}
#    spec:
#      containers:
##      - image: ge2rg312qe/ui # Не забудьте подставить свой образ
#      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#        name: ui
#        ports:
##        - containerPort: 9292
#        - containerPort: {{ .Values.service.internalPort }}
#          name: ui
#          protocol: TCP
#        env:
#        - name: ENV
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.namespace
#
# Page-50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: reddit
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui
      labels:
        app: reddit
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: ui
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: ui
        env:
        - name: POST_SERVICE_HOST
          value: {{  .Values.postHost | default (printf "%s-post" .Release.Name) }}
        - name: POST_SERVICE_PORT
          value: {{  .Values.postPort | default "5000" | quote }}
        - name: COMMENT_SERVICE_HOST
          value: {{  .Values.commentHost | default (printf "%s-comment" .Release.Name) }}
        - name: COMMENT_SERVICE_PORT
          value: {{  .Values.commentPort | default "9292" | quote }}
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
