# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ui
#   labels:
#     app: reddit
#     component: ui
# spec:
#   type: NodePort
#   ports:
#   - port: 9292
#     protocol: TCP
#     targetPort: 9292
#   selector:
#     app: reddit
#     component: ui
# page-15!!!
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
#    targetPort: 9292
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
