version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - reddit_db:/data/db
    networks:
      back_net:
        aliases:
        - comment_db
        - post_db
  ui:
    image: ${USER_NAME}/ui:${TAG_UI}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - ${PORT_UI}:9292/tcp
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post:${TAG_POST}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    networks:
      - front_net
      - back_net

  comment:
    image: ${USER_NAME}/comment:${TAG_COMMENT}
    environment:
      - COMMENT_DATABASE_HOST=comment_db
      - COMMENT_DATABASE=comments
    networks:
      - front_net
      - back_net

volumes:
  reddit_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.11.0/28
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.11.16/28
