---
- name: Install Docker
  hosts: all
  become: true
  tasks:

    - name: install transport-https and certs-pkgs
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python-pip
        update_cache: yes
        state: present

    - name: add key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://download.docker.com/linux/ubuntu bionic stable
        update_cache: yes
        state: present

    - name: install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present

    - name: Install Docker Module for Python
      pip:
        name: docker-py
        executable: pip

    - name: Enable service
      service:
        name: docker
        state: started
        enabled: yes
