---
- name: run reddit
  hosts: all
  become: true
  tasks:
  - name: Wait connect
    wait_for_connection:
  - name: docker
    docker_container:
      name: reddit
      image: ge2rg312qe/otus-reddit:1.0
      ports:
        - "9292:9292"
      state: started
      restart: yes
