version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - reddit_db:/data/db
    networks:
      - reddit
  ui:
    build: ./ui
    image: ${USER}/ui:${TAG_UI}
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USER}/post:${TAG_POST}
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USER}/comment:${TAG_COMMENT}
    networks:
      - reddit

volumes:
  reddit_db:

networks:
  reddit:
