version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - reddit_db:/data/db
    networks:
      back_net:
        aliases:
        - comment_db
        - post_db
  ui:
    build: ./ui
    image: ${USER}/ui:${TAG_UI}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - ${PORT_UI}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USER}/post:${TAG_POST}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USER}/comment:${TAG_COMMENT}
    environment:
      - COMMENT_DATABASE_HOST=comment_db
      - COMMENT_DATABASE=comments
      - APP_HOME='/app'
    networks:
      - front_net
      - back_net

volumes:
  reddit_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/29
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.8/29
